"""
=============================================================================
COMIC BOOK VALIDATOR — Post-generation gap detector and repairman
=============================================================================
Validates a synthesized comic book by detecting and repairing:

  1. SKIPPED PAGES — Gaps in page numbering (e.g. pages 1,2,3,5 → page 4
     missing). Gap pages are generated by the LLM with full narrative context
     from surrounding pages so the story flows seamlessly through the repair.

  2. MISSING PANELS — Panels that exist in the layout but have no generated
     image (broken path, failed generation, or skipped entirely). Missing
     panel images are regenerated using the panel's existing script data or,
     if the script data is also missing, synthesized from the page beat.

After all repairs are applied the validator re-sorts pages, recomposes every
page image, and rebuilds the DOCX / PDF / CBZ outputs.

USAGE:
    from comic_book_validator import validate_and_repair_comic

    # After running synthesize_comic_book(...) or synthesize_and_validate(...)
    result = validate_and_repair_comic(
        working_dir="./SynthesizedComics/_work_MyComic",
        output_dir="./SynthesizedComics",
    )

    # Or as a one-shot wrapper that synthesizes + validates in sequence:
    from comic_book_validator import synthesize_and_validate

    result = synthesize_and_validate(
        story_idea_str=concept,
        target_pages=50,
        panels_per_page_avg=4,
        use_grok=True,
        image_model='ZIMAGE',
    )

=============================================================================
"""

from __future__ import annotations

import json
import logging
import os
import pickle
import random
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from PIL import Image

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(message)s")


# =============================================================================
# LAZY IMPORTS — pulled from comic_book_generator at call time so this module
# can be imported without triggering heavy model loading.
# =============================================================================

def _cbg():
    """Return the comic_book_generator module (imported once)."""
    import comic_book_generator as _m
    return _m


# =============================================================================
# SECTION 1 — ARTIFACT I/O HELPERS
# =============================================================================

def _load_artifacts(working_dir: str):
    """Load all working-directory artifacts.

    Returns
    -------
    (script, layouts_raw, manifest, project_data)
    """
    paths = {
        "script":   os.path.join(working_dir, "script.json"),
        "layouts":  os.path.join(working_dir, "layouts.json"),
        "manifest": os.path.join(working_dir, "panel_manifest.json"),
        "project":  os.path.join(working_dir, "project.pkl"),
    }
    for name, path in paths.items():
        if not os.path.exists(path):
            raise FileNotFoundError(f"Required artifact '{name}' not found: {path}")

    with open(paths["script"], encoding="utf-8") as f:
        script = json.load(f)
    with open(paths["layouts"], encoding="utf-8") as f:
        layouts_raw = json.load(f)
    with open(paths["manifest"], encoding="utf-8") as f:
        manifest = json.load(f)
    with open(paths["project"], "rb") as f:
        project_data = pickle.load(f)

    return script, layouts_raw, manifest, project_data


def _save_artifacts(working_dir: str,
                    script: List[Dict],
                    layouts_raw: List[Dict],
                    manifest: Dict) -> None:
    """Persist updated artifacts back to working_dir."""
    with open(os.path.join(working_dir, "script.json"), "w", encoding="utf-8") as f:
        json.dump(script, f, indent=2, ensure_ascii=False)
    with open(os.path.join(working_dir, "layouts.json"), "w", encoding="utf-8") as f:
        json.dump(layouts_raw, f, indent=2, ensure_ascii=False)
    with open(os.path.join(working_dir, "panel_manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)


def _layouts_raw_to_objects(layouts_raw: List[Dict]) -> list:
    """Convert raw layout dicts → PageLayout dataclass instances."""
    m = _cbg()
    result = []
    for l in layouts_raw:
        result.append(m.PageLayout(
            page_number=l["page_number"],
            template_name=l["template_name"],
            panel_count=l["panel_count"],
            panel_boxes=[tuple(b) for b in l["panel_boxes"]],
            page_title=l.get("page_title", ""),
            page_mood=l.get("page_mood", ""),
            cliffhanger=l.get("cliffhanger", False),
        ))
    return result


def _layout_to_raw(layout) -> Dict:
    """Convert a PageLayout dataclass → JSON-serialisable dict."""
    return {
        "page_number":   layout.page_number,
        "template_name": layout.template_name,
        "panel_count":   layout.panel_count,
        "panel_boxes":   [list(b) for b in layout.panel_boxes],
        "page_title":    layout.page_title,
        "page_mood":     layout.page_mood,
        "cliffhanger":   layout.cliffhanger,
    }


# =============================================================================
# SECTION 2 — GAP DETECTION
# =============================================================================

def detect_gaps(script: List[Dict],
                layouts_raw: List[Dict],
                manifest: Dict) -> Dict[str, Any]:
    """Scan the comic for missing pages and missing panel images.

    Special pages (_act_break, _prologue, _narration_splash, _act_interstitial)
    are excluded from gap detection: they are synthesized on demand and do not
    form part of the numbered story-page sequence.

    Returns
    -------
    {
        'script_page_numbers':       set[int],
        'expected_range':            range,
        'missing_pages':             List[int],
        'pages_with_missing_panels': Dict[int, List[int]],
        'total_issues':              int,
        'summary':                   str,
    }
    """
    def _is_special(page: Dict) -> bool:
        """True for non-story pages that skip normal numbering."""
        return bool(
            page.get("_act_break")
            or page.get("_prologue")
            or page.get("_narration_splash")
            or page.get("_act_interstitial")
            or page.get("importance") in ("act_interstitial", "narration_splash")
            or page.get("beat_type") in ("act_interstitial", "narration_splash")
        )

    # ── Index script by page number (story pages only) ──────────────────────
    script_by_page: Dict[int, Dict] = {}
    special_page_nums: set = set()   # page numbers occupied by act-break / special pages
    for page in script:
        pnum = page.get("page")
        if pnum is None:
            continue
        if _is_special(page) or page.get("_act_break"):
            # Act-break and other special pages occupy a page-number slot but
            # are not story pages. Record their numbers so detect_gaps does NOT
            # report those slots as missing — the act-break card IS the content.
            special_page_nums.add(int(pnum))
        else:
            script_by_page[int(pnum)] = page

    # ── Index layouts by page number ─────────────────────────────────────────
    layout_by_page: Dict[int, Dict] = {}
    for l in layouts_raw:
        pnum = l.get("page_number")
        if pnum is not None:
            layout_by_page[int(pnum)] = l

    all_page_nums = sorted(script_by_page)
    if not all_page_nums:
        return {
            "script_page_numbers":       set(),
            "expected_range":            range(0),
            "missing_pages":             [],
            "pages_with_missing_panels": {},
            "total_issues":              0,
            "summary":                   "No story pages found in script.json.",
        }

    min_page = 1
    max_page = max(all_page_nums)
    expected = set(range(min_page, max_page + 1))
    present  = set(all_page_nums)
    # A page-number slot is genuinely missing ONLY if it is neither a story
    # page NOR a special page (act-break, narration-splash, interstitial).
    # Without this exclusion, the act-break pages' slots (e.g. page 1, 23, 45)
    # are wrongly treated as gaps and the validator overwrites the act-break
    # title cards with newly-generated generic story pages.
    missing_pages = sorted((expected - present) - special_page_nums)

    # ── Detect panels with missing / broken image files ──────────────────────
    pages_with_missing_panels: Dict[int, List[int]] = {}

    for page_num, page in script_by_page.items():
        page_key = f"page_{page_num:03d}"
        page_manifest = manifest.get(page_key, {})

        layout = layout_by_page.get(page_num, {})
        panel_count = layout.get("panel_count", len(page.get("panels") or []))

        bad_panels: List[int] = []
        for panel_idx in range(1, panel_count + 1):
            panel_key = f"panel_{panel_idx:02d}"
            record = page_manifest.get(panel_key)

            if not record:
                bad_panels.append(panel_idx)
                continue

            active   = record.get("active_variant", 1)
            variants = record.get("variants", [])
            img_path = None
            for v in variants:
                if v.get("index") == active:
                    img_path = v.get("path")
                    break
            if img_path is None and variants:
                img_path = variants[0].get("path")

            if not img_path or not os.path.exists(img_path):
                bad_panels.append(panel_idx)

        if bad_panels:
            pages_with_missing_panels[page_num] = bad_panels

    # Also check special pages (narration/interstitial/act-break) for missing
    # panel images — but only report, never treat them as "missing pages" since
    # they already exist in the script as valid structured content.
    for page in script:
        if not (_is_special(page) or page.get("_act_break")):
            continue
        pnum = page.get("page")
        if pnum is None:
            continue
        pnum = int(pnum)
        page_key = f"page_{pnum:03d}"
        page_manifest = manifest.get(page_key, {})
        record = page_manifest.get("panel_01", {})
        if record:
            variants = record.get("variants", [])
            active   = record.get("active_variant", 1)
            img_path = None
            for v in variants:
                if v.get("index") == active:
                    img_path = v.get("path")
                    break
            if img_path is None and variants:
                img_path = variants[0].get("path")
            if not img_path or not os.path.exists(img_path):
                # Panel image missing for a special page — note it but don't
                # count it toward missing_pages (don't regenerate the whole page)
                logger.warning(
                    f"  [Validate] Special page {pnum} ({page.get('title','')}) "
                    f"has no panel image at {img_path!r}; editor can regenerate."
                )

    total = len(missing_pages) + sum(len(v) for v in pages_with_missing_panels.values())

    lines = [f"Validation found {total} issue(s):"]
    if not total:
        lines = ["Validation passed: all pages and panels are present ✓"]
    else:
        if missing_pages:
            lines.append(f"  • {len(missing_pages)} missing page(s): {missing_pages}")
        if pages_with_missing_panels:
            for pg, panels in sorted(pages_with_missing_panels.items()):
                lines.append(f"  • Page {pg}: missing panel image(s) {panels}")

    return {
        "script_page_numbers":       present,
        "expected_range":            range(min_page, max_page + 1),
        "missing_pages":             missing_pages,
        "pages_with_missing_panels": pages_with_missing_panels,
        "total_issues":              total,
        "summary":                   "\n".join(lines),
    }


# =============================================================================
# SECTION 3 — GAP REPAIR: Missing pages (script + images)
# =============================================================================

def _page_context_snippet(page: Dict, role: str) -> str:
    """One-line context string from a page dict for LLM prompting."""
    title   = page.get("title", "")
    beat    = page.get("beat", "")
    setting = page.get("setting", "")
    tone    = page.get("emotional_tone", "")
    panels  = page.get("panels") or []

    edge_desc = ""
    if panels:
        target_panel = panels[-1] if role == "preceding" else panels[0]
        if isinstance(target_panel, dict):
            edge_desc = (target_panel.get("description") or "")[:100]

    label = "ends with" if role == "preceding" else "opens with"
    return (
        f"Title: {title!r} | Beat: {beat} | "
        f"Setting: {setting} | Tone: {tone} | {label}: {edge_desc}"
    )


def _normalise_panels(raw_panels: list, fallback_context: str, page_num: int) -> List[Dict]:
    """Coerce whatever the LLM returned into clean panel dicts."""
    clean = []
    for idx, panel in enumerate(raw_panels, 1):
        if isinstance(panel, dict):
            panel["panel_index"] = idx
            if not (panel.get("description") or "").strip():
                panel["description"] = fallback_context or f"Story moment on page {page_num}"
            clean.append(panel)
        else:
            clean.append({
                "panel_index":        idx,
                "description":        str(panel) if panel else fallback_context,
                "composition":        "medium_shot",
                "camera_angle":       "eye_level",
                "mood":               "",
                "characters_in_frame": [],
                "sensory_anchor":     "",
                "importance":         "standard",
                "dialogue":           [],
                "sfx":                [],
            })
    return clean


def generate_gap_page_scripts(missing_pages: List[int],
                               script: List[Dict],
                               project,
                               panels_per_page_avg: int = 4) -> List[Dict]:
    """Generate complete panel scripts for each missing page.

    Each gap page is created by asking the LLM to bridge the narrative
    gap using the surrounding pages as context.
    """
    if not missing_pages:
        return []

    m = _cbg()

    script_by_page: Dict[int, Dict] = {}
    for pg in script:
        if pg.get("_act_break") or pg.get("_prologue"):
            continue
        pnum = pg.get("page")
        if pnum is not None:
            script_by_page[int(pnum)] = pg

    all_nums = sorted(script_by_page)
    si = project.story_idea
    generated: List[Dict] = []

    for page_num in missing_pages:
        logger.info(f"  Generating script for missing page {page_num}…")

        preceding_nums = [n for n in all_nums if n < page_num]
        following_nums = [n for n in all_nums if n > page_num]
        pre_page  = script_by_page.get(preceding_nums[-1]) if preceding_nums else None
        post_page = script_by_page.get(following_nums[0])  if following_nums else None

        pre_summary  = (_page_context_snippet(pre_page,  "preceding")
                        if pre_page  else "Beginning of story")
        post_summary = (_page_context_snippet(post_page, "following")
                        if post_page else "End of story")

        context_lines = []
        for n in (preceding_nums[-4:] + following_nums[:4]):
            pg = script_by_page.get(n)
            if pg:
                context_lines.append(
                    f"  Page {n}: {pg.get('beat', '')} [{pg.get('emotional_tone', '')}]"
                )
        wider_context = "\n".join(context_lines) or "  (no wider context)"

        pre_page_num  = preceding_nums[-1] if preceding_nums else "?"
        post_page_num = following_nums[0]  if following_nums else "?"
        min_panels    = max(1, panels_per_page_avg - 1)
        max_panels    = panels_per_page_avg + 1

        prompt = (
            "You are a comic book writer. A page is MISSING from the story "
            "and must be written to maintain narrative continuity.\n\n"
            f"STORY CONTEXT:\n"
            f"  Genre:   {si.genre}\n"
            f"  Mood:    {si.mood}\n"
            f"  Premise: {si.premise[:300]}\n\n"
            f"MISSING PAGE: {page_num}\n\n"
            f"PRECEDING PAGE ({pre_page_num}):\n  {pre_summary}\n\n"
            f"FOLLOWING PAGE ({post_page_num}):\n  {post_summary}\n\n"
            f"SURROUNDING PAGES (for broader continuity):\n{wider_context}\n\n"
            f"Write page {page_num} so it bridges the preceding page's final "
            "moment to the following page's opening beat. Requirements:\n"
            f"  • Follow naturally from the preceding page\n"
            f"  • Lead naturally into the following page\n"
            f"  • Maintain genre, mood and premise\n"
            f"  • Include {min_panels}–{max_panels} panels\n\n"
            "Return a SINGLE JSON object (no markdown, no explanation):\n"
            "{\n"
            f'  "page": {page_num},\n'
            '  "title": "evocative 3-6 word title",\n'
            '  "setting": "vivid setting description",\n'
            '  "characters_present": ["name1"],\n'
            '  "beat": "single sentence — the story beat this page delivers",\n'
            '  "beat_id": "",\n'
            '  "emotional_tone": "one evocative phrase",\n'
            '  "visual_hook": "the panel a reader scans first",\n'
            '  "cliffhanger": false,\n'
            '  "importance": "standard",\n'
            '  "panels": [\n'
            '    {\n'
            '      "panel_index": 1,\n'
            '      "description": "WHAT IS IN FRAME — visual, specific, concrete",\n'
            '      "composition": "medium_shot",\n'
            '      "camera_angle": "eye_level",\n'
            '      "mood": "evocative phrase",\n'
            '      "characters_in_frame": ["name1"],\n'
            '      "sensory_anchor": "one specific sensory detail",\n'
            '      "importance": "standard",\n'
            '      "dialogue": [{"speaker":"NAME","text":"Short line.","bubble_type":"speech","position_hint":"top-left"}],\n'
            '      "sfx": []\n'
            '    }\n'
            '  ]\n'
            "}"
        )

        try:
            response = m.get_openai_prompt_response(
                prompt, temperature=0.7, max_completion_tokens=75000,
                openai_model=m.openai_model_large, use_grok=m.USE_GROK,
            )
            parsed = m.parse_json_response(response)

            if parsed and isinstance(parsed, dict) and parsed.get("panels"):
                parsed["page"] = page_num
                fallback_beat  = parsed.get("beat", f"Story beat on page {page_num}")
                parsed["panels"] = _normalise_panels(
                    parsed["panels"], fallback_beat, page_num
                )
                generated.append(parsed)
                logger.info(
                    f"    ✓ Page {page_num}: '{parsed.get('title','')}' "
                    f"({len(parsed['panels'])} panels)"
                )
                continue

        except Exception as exc:
            logger.warning(f"    LLM failed for gap page {page_num}: {exc}")

        # ── Fallback: minimal page derived from surrounding beats ────────────
        pre_beat  = (pre_page  or {}).get("beat", "")
        post_beat = (post_page or {}).get("beat", "")
        ref_page  = pre_page or post_page or {}

        fallback: Dict[str, Any] = {
            "page":               page_num,
            "title":              f"Page {page_num}",
            "setting":            ref_page.get("setting", ""),
            "characters_present": ref_page.get("characters_present", []),
            "beat":               f"Transition from [{pre_beat[:80]}] to [{post_beat[:80]}]",
            "beat_id":            "",
            "emotional_tone":     ref_page.get("emotional_tone", ""),
            "visual_hook":        "dramatic transition",
            "cliffhanger":        False,
            "importance":         "standard",
            "panels": [
                {
                    "panel_index":        i + 1,
                    "description":        (
                        pre_beat[:120]  if i == 0
                        else post_beat[:120] if i == panels_per_page_avg - 1
                        else f"Transition moment {i+1} bridging the narrative gap"
                    ),
                    "composition":        "medium_shot",
                    "camera_angle":       "eye_level",
                    "mood":               ref_page.get("emotional_tone", "dramatic"),
                    "characters_in_frame": ref_page.get("characters_present", [])[:2],
                    "sensory_anchor":     "",
                    "importance":         "standard",
                    "dialogue":           [],
                    "sfx":                [],
                }
                for i in range(panels_per_page_avg)
            ],
        }
        generated.append(fallback)
        logger.warning(f"    ⚠ Used fallback script for page {page_num}")

    return generated


# =============================================================================
# SECTION 4 — GAP REPAIR: Missing panel images
# =============================================================================

def _regenerate_panel_images(page_num: int,
                              missing_panel_indices: List[int],
                              page_script: Dict,
                              layout_raw: Dict,
                              manifest: Dict,
                              project,
                              pipe,
                              panels_dir: str,
                              panel_variants: int) -> Dict:
    """Generate images for specific panel indices that are absent or broken.

    Uses _nearest_gen_size with the true panel slot dimensions (derived from
    layout boxes + page geometry) so the generated image AR matches the
    panel slot exactly — the same approach as the main pipeline. Falls back
    to a symmetric nearest-size if layout info is unavailable.
    """
    m = _cbg()

    page_key = f"page_{page_num:03d}"
    if page_key not in manifest:
        manifest[page_key] = {}
    page_manifest = manifest[page_key]

    # ── Emotional arc state and DNA ──────────────────────────────────────────
    emotional_arc = (project.story_dna or {}).get('_emotional_arc', {})
    arc_state     = emotional_arc.get(page_num, {})
    page_dna      = m.build_page_dna(page_script, project.story_dna, page_num, arc_state)

    # ── Active image model ───────────────────────────────────────────────────
    import novel_generator as _ng
    _active_model = getattr(_ng, 'IMAGE_MODEL', None)

    # ── Panel script lookup ──────────────────────────────────────────────────
    panel_scripts: Dict[int, Dict] = {}
    for ps in (page_script.get("panels") or []):
        if isinstance(ps, dict):
            idx = ps.get("panel_index")
            if idx:
                panel_scripts[int(idx)] = ps

    panel_boxes = layout_raw.get("panel_boxes", [])
    all_panel_indices = sorted(panel_scripts.keys()) or list(range(1, len(panel_boxes) + 1))

    # ── Compute true pixel slot dimensions once for all panels on this page ──
    # Build a minimal PageLayout so _compute_page_panel_pixel_dims can derive
    # the exact panel slot sizes (margins + gutters applied), matching how the
    # main pipeline sizes images.
    try:
        _tmp_layout = m.PageLayout(
            page_number   = page_num,
            template_name = layout_raw.get("template_name", ""),
            panel_count   = layout_raw.get("panel_count", len(panel_boxes)),
            panel_boxes   = [tuple(b) for b in panel_boxes],
            page_title    = layout_raw.get("page_title", ""),
            page_mood     = layout_raw.get("page_mood", ""),
            cliffhanger   = layout_raw.get("cliffhanger", False),
        )
        _pixel_dims = m._compute_page_panel_pixel_dims(_tmp_layout)
    except Exception:
        _pixel_dims = []

    # ── Continuity anchors ───────────────────────────────────────────────────
    def _panel_summary(pidx: int) -> str:
        ps = panel_scripts.get(pidx, {})
        desc = (ps.get('description', '') or '').strip()[:130]
        comp = ps.get('composition', '')
        return f"{desc} [{comp}]" if comp else desc

    min_panel = min(all_panel_indices, default=1)
    first_panel_is_missing = (min_panel in missing_panel_indices)

    page_anchor_ctx: Optional[Dict] = None
    if not first_panel_is_missing:
        for pidx in sorted(all_panel_indices):
            if pidx not in missing_panel_indices:
                page_anchor_ctx = {
                    'summary':        _panel_summary(pidx),
                    'palette_state':  arc_state.get('palette_state', ''),
                    'lighting_state': arc_state.get('lighting_state', ''),
                }
                break

    # Reorder: generate panel 1 first (it defines scene space)
    ordered_missing = list(missing_panel_indices)
    if first_panel_is_missing and min_panel in ordered_missing:
        ordered_missing.remove(min_panel)
        ordered_missing.insert(0, min_panel)

    for panel_idx in ordered_missing:
        panel_key = f"panel_{panel_idx:02d}"
        logger.info(f"    Generating images: page {page_num} panel {panel_idx}…")

        # ── Build panel script ───────────────────────────────────────────────
        ps = panel_scripts.get(panel_idx)
        if not ps:
            n_panels = len(all_panel_indices) or 4
            if panel_idx == min(all_panel_indices, default=1):
                comp = 'establishing'
            elif panel_idx == max(all_panel_indices, default=n_panels):
                comp = 'close_up'
            else:
                comp = 'medium_shot'
            ps = {
                "panel_index":         panel_idx,
                "description":         (page_script.get("beat")
                                         or page_script.get("title")
                                         or f"Story moment on page {page_num}"),
                "composition":         comp,
                "camera_angle":        "eye_level",
                "mood":                page_script.get("emotional_tone", ""),
                "characters_in_frame": page_script.get("characters_present", []),
                "sensory_anchor":      page_script.get("visual_hook", ""),
                "importance":          "standard",
                "dialogue":            [],
                "sfx":                 [],
            }

        # ── Panel DNA ────────────────────────────────────────────────────────
        panel_dna = m.build_panel_dna(ps, page_dna, project.story_dna, arc_state)

        # ── Previous-panel continuity ────────────────────────────────────────
        prev_panel_ctx: Optional[Dict] = None
        prev_idx = panel_idx - 1
        if prev_idx >= 1:
            prev_summary = _panel_summary(prev_idx)
            if prev_summary:
                prev_panel_ctx = {
                    'summary': prev_summary,
                    'transition_style': arc_state.get('transition_style', ''),
                }

        # ── Scene consistency anchor ─────────────────────────────────────────
        _scene_anchor = None
        try:
            import comic_book_art_director as _ad
            _scene_anchor = _ad.build_scene_consistency_anchor(
                ps, project.characters,
                registry=project.character_registry,
                visual_bible=getattr(project, 'visual_bible', None),
            )
        except Exception as _e:
            logger.warning(f"      [SceneAnchor] regen build failed: {_e}")

        # ── Image prompt ─────────────────────────────────────────────────────
        prompt = m.compose_panel_prompt(
            ps, project.story_idea, project.character_registry,
            project.story_dna, page_dna, panel_dna,
            prev_panel_ctx=prev_panel_ctx,
            page_anchor_ctx=page_anchor_ctx,
            visual_bible=getattr(project, 'visual_bible', None),
            scene_consistency_ctx=_scene_anchor,
        )

        # ── Image dimensions: use true panel slot AR via _nearest_gen_size ───
        # Mirror the main pipeline exactly: get the pixel slot dims from the
        # layout (margins + gutters), pass to _nearest_gen_size for the model-
        # legal (gen_w, gen_h) that best matches the slot's aspect ratio.
        box_idx = panel_idx - 1
        if 0 <= box_idx < len(_pixel_dims):
            true_w, true_h = _pixel_dims[box_idx]
        elif 0 <= box_idx < len(panel_boxes):
            # Fallback: rough estimate from box fractions × printable area
            x, y, w_pct, h_pct = panel_boxes[box_idx]
            _pw = int((8.5 - 1.0) * 300)   # printable width at 300 DPI
            _ph = int((11.0 - 1.125) * 300) # printable height at 300 DPI
            true_w = max(64, int(w_pct * _pw))
            true_h = max(64, int(h_pct * _ph))
        else:
            true_w, true_h = 1024, 1024

        gen_w, gen_h = m._nearest_gen_size(true_w, true_h, _active_model)

        # ── Generate variants ────────────────────────────────────────────────
        variant_records = []
        arc_intensity = float(arc_state.get('intensity', 0.5) or 0.5)
        grammar_label = panel_dna.get('grammar_label', '')

        try:
            _chars_seed  = ps.get('characters_in_frame', []) or []
            _scene_setting = (ps.get('setting') or '').strip()
            _base_seed   = m._derive_base_seed(
                f"{m._scene_seed_key(_scene_setting, _chars_seed)}|panel{panel_idx}"
            )
        except Exception:
            _base_seed = random.randint(0, m.MAX_SEED)

        for v_idx in range(panel_variants):
            seed       = (_base_seed + v_idx * 0x9E3779B1) % (m.MAX_SEED + 1)
            variant_no = v_idx + 1
            fname      = f"{page_key}_{panel_key}_variant_{variant_no:02d}.jpg"
            save_path  = os.path.join(panels_dir, fname)
            try:
                img = m._safe_gen_image(
                    pipe, prompt, height=gen_h, width=gen_w,
                    seed=seed, num_inference_steps=m.N_STEPS,
                    promptEnhance=False,
                )
                img_np   = np.array(img)
                enhanced = m.comic_panel_pipeline(
                    img_np,
                    grammar_label=grammar_label,
                    arc_intensity=arc_intensity,
                )
                try:
                    _vscore, _ = m._score_panel_variant(enhanced)
                except Exception:
                    _vscore = -1e9
                Image.fromarray(enhanced).save(
                    save_path, format="JPEG",
                    quality=m.PRINT_PANEL_JPEG_QUALITY, optimize=True,
                )
                variant_records.append({
                    "index": variant_no, "path": save_path,
                    "seed": seed, "score": _vscore,
                })
            except Exception as exc:
                logger.warning(f"      Variant {variant_no} failed: {exc}")

        if variant_records:
            try:
                _best = m._select_best_variant(variant_records)
            except Exception:
                _best = 1
            page_manifest[panel_key] = {
                "active_variant":  _best,
                "prompt":          prompt,
                "description":     ps.get("description", ""),
                "variants":        variant_records,
                "true_panel_w":    true_w,
                "true_panel_h":    true_h,
                "gen_dims":        [gen_w, gen_h],
                "visual_grammar":  grammar_label,
                "arc_intensity":   arc_intensity,
                "arc_stage":       arc_state.get('stage', ''),
            }
            logger.info(f"      ✓ {len(variant_records)} variant(s) generated "
                        f"(selected variant {_best})")

            # After generating panel 1, use it as the page anchor
            if page_anchor_ctx is None or panel_idx == min_panel:
                page_anchor_ctx = {
                    'summary':        ps.get('description', '')[:130],
                    'palette_state':  arc_state.get('palette_state', ''),
                    'lighting_state': arc_state.get('lighting_state', ''),
                }
        else:
            logger.warning(f"      ✗ All variants failed for page {page_num} panel {panel_idx}")

    return manifest


# =============================================================================
# SECTION 5 — SORTED INSERTION HELPERS
# =============================================================================

def _insert_sorted_by_page(script: List[Dict], new_page: Dict) -> None:
    """Insert new_page into script at the correct position (sorted by page num)."""
    page_num = int(new_page.get("page", 0))
    for i, pg in enumerate(script):
        if int(pg.get("page", 0)) > page_num:
            script.insert(i, new_page)
            return
    script.append(new_page)


def _insert_sorted_by_page_num(layouts_raw: List[Dict], new_layout: Dict) -> None:
    """Insert new_layout into layouts_raw sorted by page_number."""
    page_num = int(new_layout.get("page_number", 0))
    for i, l in enumerate(layouts_raw):
        if int(l.get("page_number", 0)) > page_num:
            layouts_raw.insert(i, new_layout)
            return
    layouts_raw.append(new_layout)


# =============================================================================
# SECTION 6 — MAIN VALIDATOR / REPAIRMAN
# =============================================================================

def validate_and_repair_comic(
    working_dir:         str,
    output_dir:          str,
    panels_per_page_avg: int           = 4,
    pipe                               = None,
    panel_variants:      Optional[int] = None,
    use_grok:            Optional[bool] = None,
    image_model:         Optional[str]  = None,
) -> Dict[str, Any]:
    """Validate and repair a synthesized comic book.

    Detects skipped pages and missing panel images, repairs all issues, then
    rebuilds the DOCX / PDF / CBZ with the SAME filenames as the primary
    synthesis outputs ({title}_comic.docx / .pdf / .cbz) — no _validated
    suffix. Repaired files overwrite the originals so there is always exactly
    one complete set of outputs.

    Parameters
    ----------
    working_dir         Path to the comic's working directory (contains
                        script.json, layouts.json, panel_manifest.json,
                        project.pkl).
    output_dir          Directory for rebuilt output files.
    panels_per_page_avg Average panels per page when generating gap pages.
    pipe                Optional pre-loaded image pipeline.
    panel_variants      Variants per missing panel (default: PANEL_VARIANTS).
    use_grok            Override USE_GROK for this run.
    image_model         Override IMAGE_MODEL for this run.

    Returns
    -------
    {
        'issues_found':              int,
        'missing_pages':             List[int],
        'pages_with_missing_panels': Dict[int, List[int]],
        'docx':  str, 'pdf': str, 'cbz': str,
        'working_dir': str,
    }
    """
    m = _cbg()

    import novel_generator as _ng
    _orig_use_grok    = _ng.USE_GROK
    _orig_image_model = _ng.IMAGE_MODEL
    if use_grok is not None:
        _ng.USE_GROK = bool(use_grok)
        if hasattr(m, 'USE_GROK'):
            m.USE_GROK = _ng.USE_GROK
    if image_model is not None:
        if image_model not in ('ZIMAGE', 'ERNIE', 'CHROMA', 'LENS', 'KLEIN2'):
            raise ValueError(
                f"image_model must be 'ZIMAGE', 'ERNIE', 'CHROMA', 'LENS', or 'KLEIN2',"
                f" got {image_model!r}"
            )
        _ng.IMAGE_MODEL = image_model
    if panel_variants is None:
        panel_variants = m.PANEL_VARIANTS

    logger.info("=" * 62)
    logger.info("COMIC BOOK VALIDATOR — Detecting gaps…")
    logger.info("=" * 62)

    # ── 1. Load ──────────────────────────────────────────────────────────────
    script, layouts_raw, manifest, project_data = _load_artifacts(working_dir)
    project     = project_data["project"]
    cover_paths = project_data.get("cover_paths", [])
    logger.info(f"Loaded: {len(script)} script pages, {len(layouts_raw)} layouts")

    # ── 2. Detect ─────────────────────────────────────────────────────────────
    gap_report = detect_gaps(script, layouts_raw, manifest)
    logger.info("\n" + gap_report["summary"])

    missing_pages             = gap_report["missing_pages"]
    pages_with_missing_panels = gap_report["pages_with_missing_panels"]

    # ── Output paths — always _comic.* (never _validated) ────────────────────
    safe = m.cleanup_special_chars(project.title)
    m.create_directory_if_not_exists(output_dir)
    docx_path = os.path.join(output_dir, f"{safe}_comic.docx")
    pdf_path  = os.path.join(output_dir, f"{safe}_comic.pdf")
    cbz_path  = os.path.join(output_dir, f"{safe}_comic.cbz")
    pkl_path  = os.path.join(working_dir, "project.pkl")

    # ── 3. Short-circuit if nothing to repair ─────────────────────────────────
    if not gap_report["total_issues"]:
        logger.info("\nNo repairs needed. Rebuilding outputs from current state…")
        layouts    = _layouts_raw_to_objects(layouts_raw)
        page_paths = m.compose_all_pages(project, script, layouts, manifest)
        m.assemble_docx(project, page_paths, cover_paths, docx_path,
                        manifest=manifest, page_count=len(page_paths),
                        script=script, layouts=layouts)
        m.assemble_pdf(page_paths, cover_paths, pdf_path, project,
                       manifest=manifest)
        m.assemble_cbz(page_paths, cover_paths, cbz_path,
                       project_pkl=pkl_path if os.path.exists(pkl_path) else None,
                       manifest=manifest)
        _ng.USE_GROK    = _orig_use_grok
        _ng.IMAGE_MODEL = _orig_image_model
        if hasattr(m, 'USE_GROK'):
            m.USE_GROK = _orig_use_grok
        return {
            "issues_found":              0,
            "missing_pages":             [],
            "pages_with_missing_panels": {},
            "docx": docx_path, "pdf": pdf_path, "cbz": cbz_path,
            "working_dir": working_dir,
        }

    # ── 4. Load image pipeline ────────────────────────────────────────────────
    own_pipe = pipe is None
    if own_pipe:
        logger.info("\nLoading image generation pipeline…")
        pipe = m.load_ImageZ_pipe()

    panels_dir = os.path.join(working_dir, "panels")
    m.create_directory_if_not_exists(panels_dir)

    try:
        # ── 5. Repair: missing pages ──────────────────────────────────────────
        if missing_pages:
            logger.info(f"\n{'─'*50}")
            logger.info(f"Repairing {len(missing_pages)} missing page(s): {missing_pages}")
            logger.info("─" * 50)

            new_page_scripts = generate_gap_page_scripts(
                missing_pages, script, project, panels_per_page_avg
            )

            for new_page in new_page_scripts:
                page_num    = int(new_page["page"])
                raw_panels  = new_page.get("panels") or []
                panel_count = max(1, len(raw_panels))

                # Use the current emotional arc state for layout selection
                emotional_arc = (project.story_dna or {}).get('_emotional_arc', {})
                arc_state = emotional_arc.get(page_num, {})
                arc_intensity = float(arc_state.get('intensity', 0.5) or 0.5)

                template = m._pick_layout_template(
                    panel_count,
                    new_page.get("importance", "standard"),
                    last_panel_importance=((raw_panels[-1].get("importance", "standard")
                                            if raw_panels else "standard")),
                    page_number=page_num,
                    arc_intensity=arc_intensity,
                    is_cliffhanger=bool(new_page.get("cliffhanger", False)),
                )
                boxes = list(m.LAYOUT_TEMPLATES.get(template,
                                                     m.LAYOUT_TEMPLATES["two_by_two_4"]))
                boxes = boxes[:panel_count]
                # Apply the gap-fill pass so panels always tile the full page
                boxes = m._fill_layout_gaps(boxes)

                new_layout = m.PageLayout(
                    page_number   = page_num,
                    template_name = template,
                    panel_count   = len(boxes),
                    panel_boxes   = boxes,
                    page_title    = new_page.get("title", ""),
                    page_mood     = new_page.get("emotional_tone", ""),
                    cliffhanger   = bool(new_page.get("cliffhanger", False)),
                )
                new_layout_raw = _layout_to_raw(new_layout)

                manifest = _regenerate_panel_images(
                    page_num              = page_num,
                    missing_panel_indices = list(range(1, len(boxes) + 1)),
                    page_script           = new_page,
                    layout_raw            = new_layout_raw,
                    manifest              = manifest,
                    project               = project,
                    pipe                  = pipe,
                    panels_dir            = panels_dir,
                    panel_variants        = panel_variants,
                )

                _insert_sorted_by_page(script, new_page)
                _insert_sorted_by_page_num(layouts_raw, new_layout_raw)

                logger.info(f"  ✓ Page {page_num} inserted ({len(boxes)} panels)")

        # ── 6. Repair: missing panels within existing pages ───────────────────
        if pages_with_missing_panels:
            logger.info(f"\n{'─'*50}")
            logger.info(
                f"Repairing missing panels in "
                f"{len(pages_with_missing_panels)} page(s)…"
            )
            logger.info("─" * 50)

            script_by_page    = {int(pg.get("page", 0)): pg for pg in script}
            layout_raw_by_page = {int(l.get("page_number", 0)): l for l in layouts_raw}

            for page_num, bad_panels in sorted(pages_with_missing_panels.items()):
                logger.info(f"  Page {page_num}: panels {bad_panels}")
                page_script = script_by_page.get(page_num, {})
                layout_raw  = layout_raw_by_page.get(page_num, {})

                manifest = _regenerate_panel_images(
                    page_num              = page_num,
                    missing_panel_indices = bad_panels,
                    page_script           = page_script,
                    layout_raw            = layout_raw,
                    manifest              = manifest,
                    project               = project,
                    pipe                  = pipe,
                    panels_dir            = panels_dir,
                    panel_variants        = panel_variants,
                )

    finally:
        if own_pipe and pipe is not None:
            try:
                del pipe
                m.reset_memory(m.device)
            except Exception:
                pass

    # ── 7. Re-sort everything by page number ──────────────────────────────────
    script.sort(key=lambda pg: int(pg.get("page", 0)))
    layouts_raw.sort(key=lambda l: int(l.get("page_number", 0)))

    # ── 8. Persist updated artifacts ──────────────────────────────────────────
    _save_artifacts(working_dir, script, layouts_raw, manifest)
    logger.info("\nUpdated artifacts saved to working directory.")

    # ── 9. Recompose all pages ─────────────────────────────────────────────────
    layouts    = _layouts_raw_to_objects(layouts_raw)
    logger.info(f"\nRecomposing {len(layouts)} pages…")
    page_paths = m.compose_all_pages(project, script, layouts, manifest)

    # ── 10. Rebuild output files ───────────────────────────────────────────────
    m.assemble_docx(project, page_paths, cover_paths, docx_path,
                    manifest=manifest, page_count=len(page_paths),
                    script=script, layouts=layouts)
    m.assemble_pdf(page_paths, cover_paths, pdf_path, project,
                   manifest=manifest)
    m.assemble_cbz(page_paths, cover_paths, cbz_path,
                   project_pkl=pkl_path if os.path.exists(pkl_path) else None,
                   manifest=manifest)

    # ── 11. Final report ───────────────────────────────────────────────────────
    repaired_pages  = len(missing_pages)
    repaired_panels = sum(len(v) for v in pages_with_missing_panels.values())

    logger.info("\n" + "=" * 62)
    logger.info("VALIDATION & REPAIR COMPLETE")
    logger.info("=" * 62)
    logger.info(f"  Issues found:           {gap_report['total_issues']}")
    logger.info(f"  Missing pages repaired:  {repaired_pages}")
    logger.info(f"  Missing panels repaired: {repaired_panels}")
    logger.info(f"  Total pages in comic:    {len(script)}")
    logger.info(f"  DOCX: {docx_path}")
    logger.info(f"  PDF:  {pdf_path}")
    logger.info(f"  CBZ:  {cbz_path}")
    logger.info("=" * 62)

    _ng.USE_GROK    = _orig_use_grok
    _ng.IMAGE_MODEL = _orig_image_model
    if hasattr(m, 'USE_GROK'):
        m.USE_GROK = _orig_use_grok

    return {
        "issues_found":              gap_report["total_issues"],
        "missing_pages":             missing_pages,
        "pages_with_missing_panels": pages_with_missing_panels,
        "docx":        docx_path,
        "pdf":         pdf_path,
        "cbz":         cbz_path,
        "working_dir": working_dir,
    }


# =============================================================================
# SECTION 7 — CONVENIENCE WRAPPER: synthesize + validate in one call
# =============================================================================

def synthesize_and_validate(
    story_idea_str:      str,
    target_pages              = 24,
    panels_per_page_avg: int  = 4,
    creative_seeds:      Dict = None,
    cast_size:           str  = "medium",
    save_dir:            str  = "./SynthesizedComics",
    cover_variants:      int  = None,
    panel_variants:      int  = None,
    pipe                      = None,
    load_previous:       bool = False,
    previous_pickle:     str  = None,
    use_grok:            bool = None,
    image_model:         str  = None,
    scene_diversity           = 'auto',
) -> Dict[str, Any]:
    """Run synthesize_comic_book() then immediately validate_and_repair_comic().

    Parameters mirror synthesize_comic_book() exactly. Returns a merged dict
    with both synthesis and validation results (docx, pdf, cbz, working_dir,
    manifest, issues_found, missing_pages, pages_with_missing_panels).

    The final outputs are always named {title}_comic.docx / .pdf / .cbz —
    validation is a quality-assurance pass, not a separate deliverable. There
    are never *_validated.* files produced by this function.

    Usage
    -----
    from comic_book_validator import synthesize_and_validate

    result = synthesize_and_validate(
        story_idea_str=STORY_IDEA,
        cast_size='auto',
        target_pages='auto',
        panels_per_page_avg=3,
        use_grok=True,
        image_model='ZIMAGE',
    )
    print(result["pdf"])
    """
    m = _cbg()

    synth_kwargs: Dict[str, Any] = dict(
        story_idea_str      = story_idea_str,
        target_pages        = target_pages,
        panels_per_page_avg = panels_per_page_avg,
        creative_seeds      = creative_seeds,
        cast_size           = cast_size,
        save_dir            = save_dir,
        load_previous       = load_previous,
        previous_pickle     = previous_pickle,
    )
    if cover_variants is not None:
        synth_kwargs['cover_variants'] = cover_variants
    if panel_variants is not None:
        synth_kwargs['panel_variants'] = panel_variants
    if pipe is not None:
        synth_kwargs['pipe'] = pipe
    if use_grok is not None:
        synth_kwargs['use_grok'] = use_grok
    if image_model is not None:
        synth_kwargs['image_model'] = image_model
    if scene_diversity != 'auto':
        synth_kwargs['scene_diversity'] = scene_diversity

    logger.info("Phase A: Synthesizing comic book…")
    synth_result = m.synthesize_comic_book(**synth_kwargs)

    working_dir = synth_result["working_dir"]

    logger.info("\nPhase B: Validating and repairing…")
    repair_result = validate_and_repair_comic(
        working_dir         = working_dir,
        output_dir          = save_dir,
        panels_per_page_avg = panels_per_page_avg,
        pipe                = pipe,
        panel_variants      = panel_variants,   # pass through to repair phase
        use_grok            = use_grok,
        image_model         = image_model,
    )

    # Validation paths overwrite synthesis paths in the merged result so callers
    # always reference the latest (repaired) files.
    return {**synth_result, **repair_result}


# =============================================================================
# SECTION 8 — STANDALONE INSPECTION UTILITY (no repair)
# =============================================================================

def inspect_comic(working_dir: str) -> Dict[str, Any]:
    """Inspect a comic's working directory and report gaps without repairing.

    Useful for a quick health-check before deciding whether to repair.
    Returns the same gap_report dict as detect_gaps().
    """
    script, layouts_raw, manifest, _ = _load_artifacts(working_dir)
    gap_report = detect_gaps(script, layouts_raw, manifest)
    logger.info(gap_report["summary"])
    return gap_report


# =============================================================================
# EXAMPLE USAGE
# =============================================================================

if __name__ == "__main__":
    # ── Option A: repair an already-generated comic ──────────────────────────
    # result = validate_and_repair_comic(
    #     working_dir = "./SynthesizedComics/_work_GonzoRises",
    #     output_dir  = "./SynthesizedComics",
    # )
    # print("Repaired DOCX:", result["docx"])

    # ── Option B: synthesize + auto-validate in one call ─────────────────────
    STORY_IDEA = """
    A superhero is created, named Gonzo, when a mexican american 21 year old
    male in Houston enters an invisible portal to another planet in a far away
    galaxy.  The aliens augment his DNA and send him back to Earth.  His powers
    include telepathic abilities, empathy, and instant knowledge on any topic.
    """

    result = synthesize_and_validate(
        story_idea_str      = STORY_IDEA,
        cast_size           = 'auto',
        target_pages        = 'auto',
        panels_per_page_avg = 3,
        use_grok            = True,
        image_model         = 'ZIMAGE',
        save_dir            = "./SynthesizedComics",
    )
    print("Done!", result["docx"])
